/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TravelManagement;

import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Haikal Fikhri
 */
public class PackageTravelManagement extends javax.swing.JFrame {

 
    
    

    /**
     * Creates new form PackageTravelManagement
     */
    public PackageTravelManagement() {
        initComponents();
        buttonGroup1.add( fStandard);
        buttonGroup1.add( fEconomy);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Telephone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jTelephone = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jAddress2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Flight = new javax.swing.JLabel();
        Adult = new javax.swing.JLabel();
        Child = new javax.swing.JLabel();
        fStandard = new javax.swing.JRadioButton();
        fEconomy = new javax.swing.JRadioButton();
        jRbAdultYes = new javax.swing.JRadioButton();
        jRbChildYes = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jReceiptbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextReceipt = new javax.swing.JTextArea();
        jPrintBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        Total1 = new javax.swing.JToggleButton();
        Reset = new javax.swing.JToggleButton();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTax = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        Exit = new javax.swing.JToggleButton();
        OKbtn = new javax.swing.JToggleButton();
        DeparturePoint = new javax.swing.JLabel();
        Destination = new javax.swing.JLabel();
        Accmmodation = new javax.swing.JLabel();
        jRbInsurance = new javax.swing.JRadioButton();
        jRbAirportTax = new javax.swing.JRadioButton();
        jDeparture = new javax.swing.JComboBox<>();
        jDestination = new javax.swing.JComboBox<>();
        jAccomodation = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 5, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Travel Package Transaction");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Name.setText("Name");

        Address.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Address.setText("Address");

        Telephone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Telephone.setText("Telephone");

        Email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Email.setText("Email");

        jName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });

        jAddress.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressActionPerformed(evt);
            }
        });

        jTelephone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelephoneActionPerformed(evt);
            }
        });

        jEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });

        jAddress2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddress2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(Telephone)
                    .addComponent(Email)
                    .addComponent(Address))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jAddress)
                    .addComponent(jTelephone)
                    .addComponent(jEmail)
                    .addComponent(jAddress2))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Address)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telephone))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Email)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Flight.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Flight.setText("Flight (Please choose one)");

        Adult.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Adult.setText("Adult");

        Child.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Child.setText("Child");

        fStandard.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fStandard.setText("Standard");
        fStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fStandardActionPerformed(evt);
            }
        });

        fEconomy.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        fEconomy.setText("Economy");
        fEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fEconomyActionPerformed(evt);
            }
        });

        jRbAdultYes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRbAdultYes.setText("Yes");
        jRbAdultYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbAdultYesActionPerformed(evt);
            }
        });

        jRbChildYes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRbChildYes.setText("Yes");
        jRbChildYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbChildYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Flight)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(fStandard, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(fEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(Child)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRbChildYes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(Adult)
                                    .addGap(113, 113, 113)
                                    .addComponent(jRbAdultYes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Flight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fStandard)
                    .addComponent(fEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Adult, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRbAdultYes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbChildYes)
                    .addComponent(Child))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Receipt");

        jReceiptbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jReceiptbtn.setText("Receipt");
        jReceiptbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jReceiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReceiptbtnActionPerformed(evt);
            }
        });

        jTextReceipt.setColumns(20);
        jTextReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextReceipt);

        jPrintBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPrintBtn.setText("Print");
        jPrintBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jReceiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jReceiptbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPrintBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jlblSubTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblSubTotal.setText("Sub Total");

        jlblTax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        Total1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Total1.setText("Total");
        Total1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total1ActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jTextSubTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubTotalActionPerformed(evt);
            }
        });

        jTextTax.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jTextTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        OKbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OKbtn.setText("OK");
        OKbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSubTotal)
                            .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextTax, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSubTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DeparturePoint.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        DeparturePoint.setText("Departure Point");

        Destination.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Destination.setText("Destination");

        Accmmodation.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Accmmodation.setText("Accommodation");

        jRbInsurance.setBackground(new java.awt.Color(204, 255, 204));
        jRbInsurance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRbInsurance.setText("Travelling Insurance Paid");
        jRbInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbInsuranceActionPerformed(evt);
            }
        });

        jRbAirportTax.setBackground(new java.awt.Color(204, 255, 204));
        jRbAirportTax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRbAirportTax.setText("Airport Tax Paid");
        jRbAirportTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbAirportTaxActionPerformed(evt);
            }
        });

        jDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Senai International Airport", "Perak International Airport", "Langkawi International Airport", " " }));
        jDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartureActionPerformed(evt);
            }
        });

        jDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Kedah - Pulau Langkawi 3 Hari 2 Malam", "Perak - Pulau  Pangkor 3 Hari 2 Malam", "Johor - Pulau Tioman Mersing 3 hari 2 malam", " " }));
        jDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestinationActionPerformed(evt);
            }
        });

        jAccomodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Single", "Extra" }));
        jAccomodation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccomodationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Please fill in the details below");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap())
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(DeparturePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(Destination, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(Accmmodation)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jAccomodation, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jRbInsurance)
                                            .addComponent(jRbAirportTax))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeparturePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Destination)
                            .addComponent(jDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Accmmodation)
                            .addComponent(jAccomodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jRbInsurance)
                        .addGap(18, 18, 18)
                        .addComponent(jRbAirportTax))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddressActionPerformed

    private void jTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelephoneActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void fStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fStandardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fStandardActionPerformed

    private void fEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fEconomyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fEconomyActionPerformed

    private void jRbAdultYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbAdultYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbAdultYesActionPerformed

    private void jRbChildYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbChildYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbChildYesActionPerformed

    private void jRbInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbInsuranceActionPerformed

    private void jRbAirportTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbAirportTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbAirportTaxActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
    jTextSubTotal.setText(null); 
    jTextTax.setText(null);
    jTextTotal.setText(null);
    jName.setText(null);
    jAddress.setText(null);
    jAddress2.setText(null);
    jTelephone.setText(null);
    jEmail.setText(null);
    jDeparture.setSelectedItem("None");
    jAccomodation.setSelectedItem("None");
    jDestination.setSelectedItem("None");
    fStandard.setSelected(false);
    fEconomy.setSelected(false);
    jRbAdultYes.setSelected(false);
    jRbChildYes.setSelected(false);
    jRbAirportTax.setSelected(false);
    jRbInsurance.setSelected(false);
    
    
    }//GEN-LAST:event_ResetActionPerformed

    private void Total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total1ActionPerformed
double Kedah = 450;
double Perak = 320;
double Johor = 820;


double AccSingle = 45;

double AccExtra = 85;


double StdFlight = 2.5;
double EcoFlight = 65.5;


double AirportTax = 6.7;
double Insurance = 62.4;


double[] TravelCost = new double[20];
double iTax = 4.5;


if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected()))
{   
    TravelCost[0] = Kedah + AccSingle + StdFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Kedah + AccSingle + StdFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}




if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Kedah + AccSingle + StdFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Kedah + AccSingle + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Kedah + AccSingle + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Kedah + AccSingle + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Kedah + AccExtra + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Kedah + AccExtra + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Kedah - Pulau Langkawi 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Kedah + AccExtra + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

//=======================================================================================================
if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected()))
{   
    TravelCost[0] = Perak + AccSingle + StdFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Perak + AccSingle + StdFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}



 if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected())
{   
    TravelCost[0] = Perak + AccSingle + StdFlight + AirportTax  + Insurance ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}
 
 if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Perak + AccSingle + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Perak + AccSingle + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Perak + AccSingle + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Perak + AccExtra + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Perak + AccExtra + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Perak - Pulau  Pangkor 3 Hari 2 Malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Perak + AccExtra + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}






//==========================================================================================================
if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected()))
{   
    TravelCost[0] = Johor + AccSingle + StdFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Johor + AccSingle + StdFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}



 if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fStandard.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected())
{   
    TravelCost[0] = Johor + AccSingle + StdFlight + AirportTax +  Insurance ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}
 
 if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Johor + AccSingle + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Johor + AccSingle + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Single")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Johor + AccSingle + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected()))
{   
    TravelCost[0] = Johor + AccExtra + EcoFlight ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& jRbAirportTax.isSelected())
{   
    TravelCost[0] = Johor + AccExtra + EcoFlight + AirportTax ;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}

if ((jDestination.getSelectedItem().equals("Johor - Pulau Tioman Mersing 3 hari 2 malam"))&& 
        jAccomodation.getSelectedItem().equals("Extra")&&(fEconomy.isSelected())&& 
        jRbAirportTax.isSelected()&& jRbInsurance.isSelected() )
{   
    TravelCost[0] = Johor + AccExtra + EcoFlight + AirportTax  + Insurance;
    TravelCost[1]= ((TravelCost[0] * iTax)/100);
    String Tax =  String.format("RM%.2f", TravelCost[1]);
    jTextTax.setText((Tax));
    String subTotal =  String.format("RM%.2f", TravelCost[0]);
            jTextSubTotal.setText(subTotal);
    String Total =String.format("RM%.2f", TravelCost[0] + TravelCost[1]);
            jTextTotal.setText(Total);      
}


            String name = jName.getText().toString();
            String address = jAddress.getText().toString();
            String telephone = jTelephone.getText().toString();
            String email = jEmail.getText().toString();
 
            if(name.isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter name"); 
            } if(address.isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter address");
            } if(telephone.isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter telephone number");
            } if(email.isEmpty()){
                JOptionPane.showMessageDialog(this,"Enter email");
            }else{
                String position =null;
                if (jRbInsurance.isSelected()) { 
                    position = jRbInsurance.getText(); 
                } else if (jRbAirportTax.isSelected()) { 
                    position = jRbAirportTax.getText(); 
                }else if (position==null){
                    JOptionPane.showMessageDialog(this,"Please select  Tax paid and Insurance paid "); 
                }else{
                    PackageTravelManagement obj =new PackageTravelManagement();
                    obj.setName(name);
                    obj.setTelephone(telephone);
                    obj.setAddress(address);
                    obj.setEmail(email);
                    
                    
                }       
            }



    }//GEN-LAST:event_Total1ActionPerformed
    private JFrame frame;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        frame = new JFrame("Exit");
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit?","Travel Management System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_ExitActionPerformed

    private void jTextSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSubTotalActionPerformed

    private void jTextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalActionPerformed

    private void jAccomodationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccomodationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAccomodationActionPerformed

    private void jDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepartureActionPerformed

    private void jReceiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReceiptbtnActionPerformed
        Calendar timer = Calendar.getInstance(); 
        timer.getTime(); 
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss"); 
        String iTime= (tTime.format(timer.getTime()));
        
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        String iDate = (Tdate.format(timer.getTime()));
        
              
                int num1;    
                String ref ="";        
                num1 = 1325 + (int) (Math.random()*4238);
                ref += num1 + 1325;
               
        
        //==========================================================================
        String Name = (jName.getText());
        String Address = (jAddress.getText());
        String Address2 = (jAddress2.getText());
        String Telephone = (jTelephone.getText());
        String Email = (jEmail.getText());
        String Tax = (jTextTax.getText());
        String SubTotal = (jTextSubTotal.getText());
        String Total = (jTextTotal.getText());
        
        
        
        jTextReceipt.append("\tTravel Package Transaction\n\n"
            +"Ref:\t\t\t" + ref
            +"\n---------------------------------------" 
            +"\nName:\t\t" + Name
            +"\nAddress:\t\t"+ Address +" , "+ Address2
            +"\nTelephone:\t\t"+ Telephone
            +"\nEmail:\t\t"+ Email
            +"\nTax:\t\t"+ Tax   
            + "\nSub Total:\t\t"+ SubTotal 
            +"\nTotal:\t\t"+ Total  
            +"\n---------------------------------------" 
            +"\nDate:"+  iDate + " \tTime:" + iTime
            +"\n\n\tThanks for Using \n\tPackage Travel Management"
            +"\n\n\tBye bye ,muah ked"   
        );
    }//GEN-LAST:event_jReceiptbtnActionPerformed

    private void jPrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintBtnActionPerformed
        try{
            jTextReceipt.print();
            
        }catch (Exception e) {
           
        }
    }//GEN-LAST:event_jPrintBtnActionPerformed

    private void jAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddress2ActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        String Name = (jName.getText());
        String Address = (jAddress.getText());
        String Address2 = (jAddress2.getText());
        String Telephone = (jTelephone.getText());
        String Email = (jEmail.getText());
        String Tax = (jTextTax.getText());
        String SubTotal = (jTextSubTotal.getText());
        String Total = (jTextTotal.getText());
        
       
            try{

            FileWriter wr=new FileWriter("C:\\Users\\Haikal Fikhri\\Documents\\PackageTravelProject\\src\\FullCustData.txt",true); 

            wr.append("\n");

            wr.write("Name:"+ Name);
            wr.write(System.getProperty("line.separator"));
            wr.write("Address:"+ Address +"  , "+ Address2);
            wr.write(System.getProperty("line.separator"));
            wr.write("Telephone: " + Telephone);
            wr.write(System.getProperty("line.separator"));
            wr.write("Email:"+ Email);
            wr.write(System.getProperty("line.separator"));
            wr.write("Tax:"+ Tax);
            wr.write(System.getProperty("line.separator"));
            wr.write("SubTotal: " + SubTotal);
            wr.write(System.getProperty("line.separator"));
            wr.write("Total: " + Total);
            wr.write(System.getProperty("line.separator"));
            wr.write("-----------------------------------------------");
            wr.write(System.getProperty("line.separator"));
            wr.write(System.getProperty("line.separator"));
            
            wr.close();
            
            JOptionPane.showMessageDialog(rootPane,"Thank you. Your data have been registered");

        }
        catch(Exception e)
                {
                  
                 JOptionPane.showMessageDialog(rootPane,"Cannot save!");
                }
         
    }//GEN-LAST:event_OKbtnActionPerformed

    private void jDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDestinationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackageTravelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackageTravelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackageTravelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackageTravelManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackageTravelManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accmmodation;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Adult;
    private javax.swing.JLabel Child;
    private javax.swing.JLabel DeparturePoint;
    private javax.swing.JLabel Destination;
    private javax.swing.JLabel Email;
    private javax.swing.JToggleButton Exit;
    private javax.swing.JLabel Flight;
    private javax.swing.JLabel Name;
    private javax.swing.JToggleButton OKbtn;
    private javax.swing.JToggleButton Reset;
    private javax.swing.JLabel Telephone;
    private javax.swing.JToggleButton Total1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fEconomy;
    private javax.swing.JRadioButton fStandard;
    private javax.swing.JComboBox<String> jAccomodation;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jAddress2;
    private javax.swing.JComboBox<String> jDeparture;
    private javax.swing.JComboBox<String> jDestination;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jPrintBtn;
    private javax.swing.JRadioButton jRbAdultYes;
    private javax.swing.JRadioButton jRbAirportTax;
    private javax.swing.JRadioButton jRbChildYes;
    private javax.swing.JRadioButton jRbInsurance;
    private javax.swing.JButton jReceiptbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTelephone;
    private javax.swing.JTextArea jTextReceipt;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jlblTotal
     */
    public Object getJlblTotal() {
        return jlblTotal;
    }

    /**
     * @param jlblTotal the jlblTotal to set
     */
   

    /**
     * @return the jlblSubTotal
     */
    public Object getJlblSubTotal() {
        return jlblSubTotal;
    }

    public void setName(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setAddress(String position) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setEmail(String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setTelephone(String telephone) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param jlblSubTotal the jlblSubTotal to set
     */
   
}
